### PR TITLE
Make Set#pretty_print IRB::ColorPrinter friendly

### PR DESCRIPTION
**Pull request by k-tsj**
### Before
before

### After
after

### CODE REVIEW

**Review by olleolleolle — APPROVED** [review]
A nice improvement.

**Review by knu — APPROVED** [review]

**Comment by knu** [comment]
Thanks!

**Comment by k-tsj** [comment]
@knu 
It would be nice if you could merge this change into ruby/ruby by preview1 release.

Thanks.

**Comment by k-tsj** [comment]
Oops, it has been already merged. Sorry.

**Pull request merged**
