### PR TITLE
Prepare for a 1.0.0 release

### PR DESCRIPTION
**Pull request by knu**
I'm going to release 1.0.0 soon so it can be bundled with Ruby 3.0.

### CODE REVIEW

**Review by marcandre — COMMENTED** [review]
Looks good.
One question though: is there a solution for anyone using `SortedSet`?

**Comment by knu** [comment]
I’m thinking of releasing a sorted_set gem after working on this!

**Comment by marcandre** [comment]
> I’m thinking of releasing a sorted_set gem after working on this!

Good. Do you want help?

It could be nice to use `autoload` to display a better error message in case someone uses `SortedSet`. Would you like a PR for this?

**Comment by knu** [comment]
> Good. Do you want help?

Thanks!  I'll create a first draft and ask you for a review.

> It could be nice to use autoload to display a better error message in case someone uses SortedSet. Would you like a PR for this?

That sounds great.  It's worth a try!

**Comment by knu** [comment]
I just released a sorted_set gem: https://rubygems.org/gems/sorted_set

**Pull request merged**
