### PR TITLE
Define `Set#to_ary`

### PR DESCRIPTION
**Pull request by marcandre**
[Fix #16990]

### CODE REVIEW

**Comment by marcandre** [comment]
@knu Did you have a chance to look into this?

**Comment by knu** [comment]
I cannot estimate how this would cause an impact on private / in-house apps, but at the very least I want to make sure this does not break popular apps like gitlab, mastodon and discourse.  What do you think?

**Comment by marcandre** [comment]
These are good test bases 👍

I you are too worried, then we could wait until Ruby 3.0 is released, then make a separate `set` gem release with this feature?

**Comment by knu** [comment]
I'm closing this because of the compatibility issue.

**Pull request closed without merging**
